version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: globetrotter-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: globetrotter
      MYSQL_USER: gt_user
      MYSQL_PASSWORD: strongpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:

